// Web Animations API presets — generated by designlang (motionlang)
// Source: https://twenty.com/
// 2026-07-26T12:48:31.112Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './twenty.com-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  easeOut: 'cubic-bezier(0.16, 1, 0.3, 1)', // 106× on page
  custom2: 'cubic-bezier(0.4, 0, 0.2, 1)', // 28× on page
  easeInOut: 'ease', // 28× on page
  linear: 'linear', // 3× on page
  spring: 'cubic-bezier(0.34, 1.45, 0.55, 1)', // 1× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  xs: 100,
  sm: 160,
  md: 260,
  lg: 420,
};

/** @keyframes blocks reconstructed as WAAPI keyframe arrays. */
export const keyframes = {
  tableHeaderAppearH1tkdw5w: [{"opacity":"0","transform":"translateY(-2px)","offset":0},{"opacity":"1","transform":"translateY(0px)","offset":1}],
  tableRowAppearDswo5q4: [{"opacity":"0","maxHeight":"0px","offset":0},{"opacity":"1","maxHeight":"32px","offset":1}],
  promptTextSwapPmfr1z5: [{"opacity":"0","filter":"blur(2px)","transform":"translateY(4px)","offset":0},{"opacity":"1","filter":"blur()","transform":"translateY(0px)","offset":1}],
};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 260, easing: easings.easeOut, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
