// Framer Motion presets — generated by designlang (motionlang)
// Source: https://twenty.com/
// 2026-07-26T12:48:31.108Z
//
//   import { transitions, variants } from './twenty.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.16, 1, 0.3, 1], // 106× on page
  custom2: [0.4, 0, 0.2, 1], // 28× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 28× on page
  linear: [0, 0, 1, 1], // 3× on page
  spring: [0.34, 1.45, 0.55, 1], // 1× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.16,
  md: 0.26,
  lg: 0.42,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 700, damping: 12, mass: 1 },
  spring2: { type: 'spring', stiffness: 700, damping: 23, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.26, ease: easings.easeOut },
  fast:  { duration: 0.130, ease: easings.easeOut },
  slow:  { duration: 0.468, ease: easings.easeOut },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.065 } },
  },
  tableHeaderAppearH1tkdw5w: {
    hidden: {},
    show: {
      "opacity": ["0","1"],
      "transform": ["translateY(-2px)","translateY(0px)"],
      transition: transitions.base,
    },
  },
  tableRowAppearDswo5q4: {
    hidden: {},
    show: {
      "opacity": ["0","1"],
      "maxHeight": ["0px","32px"],
      transition: transitions.base,
    },
  },
  promptTextSwapPmfr1z5: {
    hidden: {},
    show: {
      "opacity": ["0","1"],
      "filter": ["blur(2px)","blur()"],
      "transform": ["translateY(4px)","translateY(0px)"],
      transition: transitions.base,
    },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
