// Motion One presets — generated by designlang (motionlang)
// Source: https://twenty.com/
// 2026-07-26T12:48:31.109Z
//
//   import { animate } from 'motion';
//   import { animations, easings, durations } from './twenty.com-motion.one.js';
//
//   animations.fadeIn('#hero');
//   animations.slideUp('.card', { delay: 0.1 });

/** Easing curves extracted from the live page, as Motion One cubic-bezier arrays. */
export const easings = {
  easeOut: [0.16, 1, 0.3, 1], // 106× on page
  custom2: [0.4, 0, 0.2, 1], // 28× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 28× on page
  linear: [0, 0, 1, 1], // 3× on page
  spring: [0.34, 1.45, 0.55, 1], // 1× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.16,
  md: 0.26,
  lg: 0.42,
};

/** Motion One spring options — pass as the `type: 'spring'` block of an animate() call. */
export const springs = {
  soft: { type: 'spring', stiffness: 700, damping: 12, mass: 1 },
  spring2: { type: 'spring', stiffness: 700, damping: 23, mass: 1 },
};

/** @keyframes blocks reconstructed as Motion One keyframe maps. */
export const keyframes = {
  tableHeaderAppearH1tkdw5w: {
    "opacity": ["0","1"],
    "transform": ["translateY(-2px)","translateY(0px)"]
  },
  tableRowAppearDswo5q4: {
    "opacity": ["0","1"],
    "maxHeight": ["0px","32px"]
  },
  promptTextSwapPmfr1z5: {
    "opacity": ["0","1"],
    "filter": ["blur(2px)","blur()"],
    "transform": ["translateY(4px)","translateY(0px)"]
  },
};

/** Animate-on-call helpers. Each takes a Motion One target + optional override. */
import { animate } from 'motion';

const _t = { duration: 0.26, easing: easings.easeOut };

export const animations = {
  fadeIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1] }, { ..._t, ...opts }),
  fadeOut: (target, opts = {}) =>
    animate(target, { opacity: [1, 0] }, { ..._t, ...opts }),
  slideUp: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [16, 0] }, { ..._t, ...opts }),
  slideDown: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [-16, 0] }, { ..._t, ...opts }),
  scaleIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], scale: [0.96, 1] }, { ..._t, ...opts }),
  pop: (target, opts = {}) =>
    animate(target, { scale: [0.9, 1] }, { ...springs.soft, ...opts }),
};

/** Site uses scroll- or view-timeline. Helpers wired to Motion One's `inView` / `scroll`. */
import { inView, scroll } from 'motion';

export const enterOnView = (target, variant = animations.slideUp) =>
  inView(target, (el) => { variant(el.target); });

export const parallaxY = (target, distance = 80) =>
  scroll(animate(target, { y: [0, -distance] }, { easing: 'linear' }));

export default { easings, durations, springs, keyframes, animations };
