// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://twenty.com/
// Generated: 2026-07-26T12:48:31.105Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#1c1c1c' | '#000000' | '#999999' | '#ffffff' | '#0000ee' | '#4a38f5' | '#0550ae' | '#666666' | '#333333' | '#0a3069' | '#eaf4ed' | '#1961ed' | '#82be9c' | '#09090b' | '#2f7468' | '#953800' | '#8250df' | '#4b5563' | '#b3b3b3' | '#377e5d' | '#a94a4f' | '#e5e7eb' | '#be123c' | '#18794e' | '#dddddd' | '#6d28d9' | '#ddf3e4' | '#ffe4e6' | '#7a4f2a' | '#1d4ed8' | '#b91c1c' | '#ede9fe' | '#ff5f57' | '#febc2e' | '#28c840' | '#d2989b' | '#d6409f' | '#8e4ec6' | '#f6e6d7' | '#35290f' | '#fef2a4' | '#424242' | '#dbeafe' | '#ffb08d' | '#edb7ff';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Host Grotesk' | 'inter' | 'Geist Mono' | 'Azeret Mono' | 'Inter' | 'Arial' | 'Times New Roman' | 'Aleo';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600' | '300';

export type SpacingToken = '1px' | '19px' | '24px' | '28px' | '40px' | '48px' | '60px' | '64px' | '68px' | '80px' | '120px' | '160px' | '208px';

export type RadiusToken = '1px' | '4px' | '7px' | '16px' | '20px' | '50px' | '56px' | '999px';

export type DurationToken = '100ms' | '160ms' | '260ms' | '420ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
