// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://attio.com/product
// Generated: 2026-07-26T12:47:27.430Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = never;
export type ColorHex  = '#030303' | '#ffffff' | '#c1c1c1';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'inter' | 'interDisplay';
export type FontSizeToken   = never;
export type FontWeightToken = '500' | '400' | '600';

export type SpacingToken = '1px' | '15px' | '20px' | '24px' | '28px' | '40px' | '48px' | '80px' | '116px' | '120px';

export type RadiusToken = '2px' | '8px' | '12px' | '16px' | '19px';

export type DurationToken = '150ms' | '200ms' | '300ms' | '700ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
