// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.pipedrive.com/en/why-pipedrive
// Generated: 2026-07-26T12:47:38.374Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#192435' | '#0000ee' | '#0d6ece' | '#017737' | '#555555' | '#ffffff' | '#6861f2' | '#27455c' | '#3860be' | '#656565' | '#0e5235' | '#f4f5f6' | '#d8d8d8' | '#e3fae1' | '#32ae88' | '#468254' | '#bbbbbb';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'Haffer';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '700' | '500';

export type SpacingToken = '1px' | '15px' | '20px' | '23px' | '30px' | '32px' | '35px' | '40px' | '44px' | '80px';

export type RadiusToken = '1px' | '4px' | '17px' | '20px' | '50px' | '100px';

export type DurationToken = '100ms' | '180ms' | '320ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
