// Auto-generated by designlang — component anatomy v2.
// Scaffolds. Wire into your token system; not a runtime library.

import * as React from 'react';

export interface CardProps {
  variant?: 'default';
  size?: 'small';
  children?: React.ReactNode;
}

export function Card({ variant = 'default', size = 'md', ...rest }: CardProps) {
  return React.createElement('div', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface ButtonProps {
  variant?: 'tertiary' | 'primary' | 'secondary';
  size?: 'small' | 'medium' | 'large';
  disabled?: boolean;
  children?: React.ReactNode;
}

export function Button({ variant = 'tertiary', size = 'md', ...rest }: ButtonProps) {
  return React.createElement('button', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface LinkProps {
  variant?: 'link';
  size?: 'md';
  children?: React.ReactNode;
}

export function Link({ variant = 'link', size = 'md', ...rest }: LinkProps) {
  return React.createElement('a', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface OtherProps {
  variant?: 'default';
  size?: 'md';
  children?: React.ReactNode;
}

export function Other({ variant = 'default', size = 'md', ...rest }: OtherProps) {
  return React.createElement('button', { 'data-variant': variant, 'data-size': size, ...rest });
}
