// Framer Motion presets — generated by designlang (motionlang)
// Source: https://www.hubspot.com/products/crm
// 2026-07-26T12:48:14.631Z
//
//   import { transitions, variants } from './hubspot.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeInOut: [0.25, 0.1, 0.25, 1], // 58× on page
  linear: [0, 0, 1, 1], // 13× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.01,
  xs: 0.1,
  sm: 0.2,
  md: 0.3,
  lg: 0.5,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.2, ease: easings.easeInOut },
  fast:  { duration: 0.100, ease: easings.easeInOut },
  slow:  { duration: 0.360, ease: easings.easeInOut },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.050 } },
  },
  bannerAnimation: {
    hidden: {},
    show: {
      "transform": ["translateY(200vh) translateZ(3e+09px)","translateY(var(--hs-banner-translate-y,0)) translateZ(3000000000px)"],
      "opacity": ["0","0","1"],
      transition: transitions.base,
    },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
