// Web Animations API presets — generated by designlang (motionlang)
// Source: https://www.hubspot.com/products/crm
// 2026-07-26T12:48:14.634Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './hubspot.com-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  easeInOut: 'ease', // 58× on page
  linear: 'linear', // 13× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  instant: 10,
  xs: 100,
  sm: 200,
  md: 300,
  lg: 500,
};

/** @keyframes blocks reconstructed as WAAPI keyframe arrays. */
export const keyframes = {
  bannerAnimation: [{"transform":"translateY(200vh) translateZ(3e+09px)","opacity":"0","offset":0},{"opacity":"0","offset":0.99},{"transform":"translateY(var(--hs-banner-translate-y,0)) translateZ(3000000000px)","opacity":"1","offset":1}],
};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 200, easing: easings.easeInOut, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
