// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.hubspot.com/products/crm
// Generated: 2026-07-26T12:48:14.628Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#1f1f1f' | '#f8f5ee' | '#000000' | '#124548' | '#15295a' | '#ff4800' | '#0000c5' | '#f0f0f0' | '#042729';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'HubSpot Sans' | 'Times New Roman' | 'HubSpot Serif' | 'Zen Kaku Gothic New';
export type FontSizeToken   = never;
export type FontWeightToken = '300' | '500' | '400';

export type SpacingToken = '1px' | '20px' | '24px' | '40px' | '48px' | '52px' | '56px' | '64px' | '68px' | '80px' | '96px' | '100px' | '165px';

export type RadiusToken = '3px' | '6px' | '16px' | '42px' | '50px';

export type DurationToken = '10ms' | '100ms' | '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
