# setup-v2-auto.ps1 — full auto: create Notion DBs + update config.js
# Usage: .\setup-v2-auto.ps1
# Prasyarat: Node.js, Git, Notion integration token sudah ada

$ErrorActionPreference = "Stop"
$ProjectRoot = "C:\Users\Syahfalah\buku-management-syahfalah"
$ScriptsDir = "$ProjectRoot\deploy\scripts"
$ConfigFile = "$ProjectRoot\deploy\v2\config.js"

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  V2 DASHBOARD - AUTO SETUP" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Token
Write-Host "[1/5] Notion Token" -ForegroundColor Yellow
$token = Read-Host "  Paste token (secret_xxx atau ntn_xxx)"
if (-not $token) {
  Write-Host "ERROR: token kosong" -ForegroundColor Red
  exit 1
}
$env:NOTION_TOKEN = $token
Write-Host "  OK" -ForegroundColor Green
Write-Host ""

# Step 2: Test token
Write-Host "[2/5] Test token..." -ForegroundColor Yellow
$headers = @{
  "Authorization" = "Bearer $token"
  "Notion-Version" = "2022-06-28"
}
try {
  $test = Invoke-RestMethod -Method Get -Uri "https://api.notion.com/v1/users/me" -Headers $headers
  Write-Host "  OK - workspace: $($test.bot.workspace_name)" -ForegroundColor Green
} catch {
  Write-Host "  FAIL - token invalid atau expired" -ForegroundColor Red
  exit 1
}
Write-Host ""

# Step 3: Create 4 DBs
Write-Host "[3/5] Create 4 Notion databases..." -ForegroundColor Yellow
Set-Location $ScriptsDir
$output = node create-notion-dbs.js 2>&1
Write-Host $output

if ($LASTEXITCODE -ne 0) {
  Write-Host "  FAIL - create DB error" -ForegroundColor Red
  exit 1
}
Write-Host "  OK" -ForegroundColor Green
Write-Host ""

# Step 4: Parse notion-ids.json
Write-Host "[4/5] Parse notion-ids.json..." -ForegroundColor Yellow
$idsFile = "$ScriptsDir\notion-ids.json"
if (-not (Test-Path $idsFile)) {
  Write-Host "  FAIL - notion-ids.json not found" -ForegroundColor Red
  exit 1
}
$ids = Get-Content $idsFile -Raw | ConvertFrom-Json
$kpiId = $ids.databases.kpi
$sowId = $ids.databases.sow
$progId = $ids.databases.program
$jobId = $ids.databases.jobdesk
$parentPage = $ids.parentPage

Write-Host "  Parent page: $parentPage"
Write-Host "  KPI:    $kpiId"
Write-Host "  SOW:    $sowId"
Write-Host "  Program:$progId"
Write-Host "  Jobdesk:$jobId"
Write-Host "  OK" -ForegroundColor Green
Write-Host ""

# Step 5: Update config.js
Write-Host "[5/5] Update deploy/v2/config.js..." -ForegroundColor Yellow
$configContent = @"
// V2 DASHBOARD CONFIG - LIVE MODE (Notion via Worker)
// Generated by setup-v2-auto.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm")
window.DASHBOARD_CONFIG = {
  workerBase: "https://titan-notion-proxy.YOUR-SUBDOMAIN.workers.dev",
  notionVersion: "2022-06-28",
  databases: {
    kpi:     "$kpiId",
    sow:     "$sowId",
    program: "$progId",
    jobdesk: "$jobId",
  },
  picList: [
    "Pak Ardian", "Bu Nisya", "Mada", "Riza",
    "Yudi (Sdek)", "Rizal", "Amir", "Novita",
    "Sinta", "Reni", "Rifki", "Reta"
  ],
  divisiList: ["Owner", "Operasional", "Marketing", "Proyek", "Media", "Admin"],
  watermark: "DOKUMEN INTERNAL - TIDAK UNTUK DISEBARLUASKAN",
  pollIntervalMs: 60000,
  mode: "live"
};
"@
$configContent | Out-File -FilePath $ConfigFile -Encoding UTF8 -NoNewline
Write-Host "  OK - config.js updated" -ForegroundColor Green
Write-Host ""

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  SELESAI (Notion side)" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Notion:" -ForegroundColor Yellow
Write-Host "  - 1 page: 'DASHBOARD PERUSAHAAN V2'"
Write-Host "  - 4 DB: KPI Tracker, SOW, Program Kerja, Jobdesk Harian"
Write-Host "  - File: notion-ids.json"
Write-Host ""
Write-Host "Sisa step (USER ACTION):" -ForegroundColor Yellow
Write-Host "  1. Buka Notion, share 4 DB ke integration 'Dashboard V2'"
Write-Host "     (click ... di tiap DB -> Connections -> add)"
Write-Host ""
Write-Host "  2. Deploy Worker (Cloudflare):"
Write-Host "     cd ..\..\notion-proxy-worker"
Write-Host "     npm install"
Write-Host "     npx wrangler login"
Write-Host "     ..\deploy\scripts\setup-worker.ps1"
Write-Host ""
Write-Host "  3. Update workerBase di config.js dengan Worker URL"
Write-Host ""
Write-Host "  4. Push ke GitHub:"
Write-Host "     cd ..\..\deploy"
Write-Host "     git add v2/config.js"
Write-Host "     git commit -m 'feat: V2 live mode'"
Write-Host "     git push"
Write-Host ""
Write-Host "Mau lanjut deploy Worker? (y/n)" -ForegroundColor Magenta
$lanjut = Read-Host
if ($lanjut -eq "y") {
  Write-Host ""
  Write-Host "Worker setup butuh interaktif (paste Notion token lagi)." -ForegroundColor Yellow
  Write-Host "Jalanin manual:"
  Write-Host "  cd C:\Users\Syahfalah\buku-management-syahfalah\notion-proxy-worker"
  Write-Host "  npm install"
  Write-Host "  npx wrangler login"
  Write-Host "  ..\deploy\scripts\setup-worker.ps1"
  Write-Host ""
}
